version: '3.7'

services:
  main:
    container_name: command-block
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${APP_PORT}:${APP_PORT}
      - 9229:9229
    # command: npm run start:dev
    # DEBUG MODE
    command: npm run start:debug
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - postgres
  postgres:
    container_name: command-block-db
    image: postgres:13.2
    networks:
      - webnet
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - 5432:5432
    volumes:
      - postgresdata:/var/lib/postgres
networks:
  webnet:
volumes:
  postgresdata:
